jwt:
  secret: 0000000000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: chem-lab
      auto-index-creation: true
server:
  port: 8080
logging:
  level:
    root: "debug"
web:
  cors:
    allowed-origins:
      - "http://localhost:4200/"
#    allowed-methods: "HEAD, GET, POST, PUT, PATCH, DELETE, OPTIONS"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "Origin"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Accept"
      - "Jwt-Token"
      - "Authorization"
      - "Accept"
      - "X-Requested-With"
      - "Access-Control-Request-Method"
      - "Access-Control-Request-Headers"
    expose-headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Jwt-Token"
      - "Authorization"
      - "Access-Control-Allow-Origin"
      - "Access-Control-Allow-Credentials"
    allow-credentials: true