jwt:
    secret: ENC[AES256_GCM,data:gPhn0NWmcSAkJRGP,iv:iCw+SBzmKehgoLZxiup4wmhIjB34dJPytzQYcsY54zE=,tag:bypWC9w23gtulqOP4Rs5Tw==,type:str]
azure:
    containerName: ENC[AES256_GCM,data:f+vF8PsWi8aXzr70fM8vEgtjgujD9Q==,iv:4aVHCAqhInSwfuQGEZaBN9/+lygW+tEneJM1GyF+R48=,tag:Ef5P6qy2xTBNLf/fFSEavw==,type:str]
    storageAccountName: ENC[AES256_GCM,data:mAfDcMXOHI2MrEa0aJGki9G+,iv:qN5cac+4XA1ewitxn2Z0O3w7Qq/KHoUrPBkRS7rzZ4M=,tag:8eTBi5O1rW32dtspL0BMsA==,type:str]
spring:
    mongodb:
        uri: ENC[AES256_GCM,data:oh/X9Lhf+zxTVP8GNCFpnqmWD2fo8OGwyy7LvyyH9Mm+hgzcybDjau69DxUJdAQHLQcpgrsJd2rRykcAidLuHiW0S9SlG/eEZ+W7lizQyGUu0ZQ2ZsDRJUtBV1IiPZQx5qVlOg==,iv:WuqYu3Nchnegcc4MWrN4H2xW0daV/8+Aw9VQLH1P3V0=,tag:PHdESIHH1VxlIvtTQ27Aog==,type:str]
    data:
        mongodb:
            auto-index-creation: ENC[AES256_GCM,data:826Wxg==,iv:9ZUtj0QrBUVm6KrWmzukuRp5qMbUjs4j4zRwp+CfSTI=,tag:2R2Qak563uUme+fFsgV/5w==,type:bool]
server:
    port: ENC[AES256_GCM,data:Qghivg==,iv:F5zL6hsh8Ckm3yBoIjZgZ5MHP+mK6PW3MaqsllYA6fw=,tag:A908PBHyifC6vhhZwRsTkg==,type:int]
web:
    cors:
        allowed-origins:
            - ENC[AES256_GCM,data:7PzkfOnCMpRJk5RTcQNXMr5gnTN0AOGhft61sNWSidZNPNO+AQjVjwQ5,iv:eqMknmZ+ACa+6dH10n/glhqynZXlTraL3Pk2OnMihOk=,tag:mLjmxyqp9lgQKeYWGRh/Hg==,type:str]
            - ENC[AES256_GCM,data:GxYxavBUvtafKgyqGuK70w3nfUlEa73WvENk+49IUUdtYja7nxJbOd8=,iv:e6ks0v50/oHWZrIv8RCgnvOxV2nL6jeTSz261ltIJQ8=,tag:RhMV9ANXmrY1e9n65VF+OA==,type:str]
            - ENC[AES256_GCM,data:hZWrxvzflQaQG0bVsQXYf0R4Tpt3WWoKVu5lQov1TQ==,iv:Llr2pUmzZAsFqmso3ohSZKnbBRUWOdadbBxBqxDSApQ=,tag:QZf0znaFD9ECsf4sj4u5CA==,type:str]
        allowed-methods:
            - ENC[AES256_GCM,data:unIV,iv:KRXLYSJVktUjrf9Uk4pdgO/v/B0C+x1XbLuqd+Moc9g=,tag:0gT9oaqLPQlT922uZrH9JQ==,type:str]
            - ENC[AES256_GCM,data:iaS8rQ==,iv:tyXHBT+Wimy1+Y9laah0IzW2pIT0dJWzCICO3sXrtD0=,tag:wqxKd03NaUyRwhcgCokEJg==,type:str]
            - ENC[AES256_GCM,data:o2tM,iv:FwmbZZ+qGtdmsWqtV8GJSkCrni6rvq8Sr0kw9X+xJZ0=,tag:nMnli28SbPVduIpjv0cGnQ==,type:str]
            - ENC[AES256_GCM,data:JSbbGrcV,iv:3/ew41YAY+DKrR/R1ro04POQbrqj6xcK9PHO+ovjWXQ=,tag:UKf12JcjhRI2gPJwQhfFAw==,type:str]
            - ENC[AES256_GCM,data:qjF/cnsAbg==,iv:6dtzPSJIDsW+GnmH0cVZVfwzP0yovYzABch4TVFroqY=,tag:pFC8TZpMeoyiHCCQoD3RCw==,type:str]
        allowed-headers:
            - ENC[AES256_GCM,data:xZCv+9Zq,iv:TCeuyESB9x36KjtfzA3+v6zcjpbRtFMQKohifVE3YdM=,tag:NpZQPkOa9R6exVT0g0XAMg==,type:str]
            - ENC[AES256_GCM,data:k33EQakz8D0xMFA8yEme5sdBoDr4/z0JagyQ,iv:tkE0WlIB4K7LHb3/bxeY8mtj4St4dDiOxq3wVpoidJ0=,tag:gX76E6XHq9k6wf3Epzg8IQ==,type:str]
            - ENC[AES256_GCM,data:WOypsc8OjWW2GU2Z,iv:oSO65IGgqR5Jy/EKWDigXSOJSbs5L6LIMU7fQdepr1M=,tag:uyD7d5Q8EhDW/agwXQ06vg==,type:str]
            - ENC[AES256_GCM,data:/mwVQFHy,iv:CXkMDya6w0kzEJpWkmJT5TxFOA4dLDQg7OdvYeOHFY4=,tag:X6vei0Re2PAl5Cx+cEIZiA==,type:str]
            - ENC[AES256_GCM,data:qAKQeOWpqmcm,iv:GSlE2u2YlF5ZF75PHcW6MtLlq5PdzYbohAPgUSWGroo=,tag:ywDcsh8VX6PcVwUhXJHcyg==,type:str]
            - ENC[AES256_GCM,data:pr2HGVvAUjuePflZiA==,iv:eA95ysTVbJfowdYN6jd7ZRFkgeCJEVF1o2c+P89+5RM=,tag:ulMpSUAy1oEuviIVAYvmYA==,type:str]
            - ENC[AES256_GCM,data:IjpwWglF,iv:vktjzIP7dR7ArP1Z5lhrve/AyB7GN1TyvjwxBvONoxc=,tag:e1J0mGMpZe8g1M2W6OqGPw==,type:str]
            - ENC[AES256_GCM,data:0GgUP7B9hcftfIbEFn1usA==,iv:9+n6jEOHOOPYYpR+XF2uQvLfmEBw36PUOHJGB1K78+c=,tag:x+bWcflkfn7x7ZWhp2ySrQ==,type:str]
            - ENC[AES256_GCM,data:Wh4c0qyij6E7PkT5owc0iA2G/tiEEblA+RO6VNQ=,iv:mS7I/iIzSZqAbRiRt5EiocQEmeYc5na0abs5YBTipg4=,tag:3FLxQ2qzwfpZDjszIRPMeg==,type:str]
            - ENC[AES256_GCM,data:tqbE0IlQLied0aunIMfWhPZEPRE62hGpAu1RpPPF,iv:HFWSiWNSsg1YHmdtO4SHXvq51AqOzmGeajKUpKM402Q=,tag:/FjMpZkOz3SH55Abmma2Qw==,type:str]
        expose-headers:
            - ENC[AES256_GCM,data:D+DGFF+r,iv:pn0P5gck5ylwrcLsNQejbkSZ9DgYjfTtla67eFYBmf0=,tag:hXTNsHFWfoT+7TQLP3cq+w==,type:str]
            - ENC[AES256_GCM,data:ANpJ3Ho7uwj9DOsv,iv:sTerU14SJyBokztb6jUlFWJxfNMITjRfZzLGmuI8QgI=,tag:lxeEgQqHdyRoLLhNKgihGg==,type:str]
            - ENC[AES256_GCM,data:AGjqLkDh,iv:DA7vlcPaQ6E8K9LOFG93YZ5ERvWXqSNEMxKSeDiGZuk=,tag:UuEH/DTGN0I870+/R5qbDw==,type:str]
            - ENC[AES256_GCM,data:nOoPMcZZHIJv,iv:ROzmmUT0W9r/app7yE9508EAErn2BMwubsLgbYkThoQ=,tag:60OMWfdzLHYBg/oVqf8RNQ==,type:str]
            - ENC[AES256_GCM,data:M39+ewxVx87YwHXPwg==,iv:4BCF8xJfqprkp0SyfICm+uRNjzVvB70H8+liY92pfSw=,tag:PN7cdlGzNCrob0MB3tUidA==,type:str]
            - ENC[AES256_GCM,data:0OhLCMefBARRuCje7sFpVFDxB1i2UGBgOpx6,iv:uJyfKKcTNvY2G+Mt2Kn0RQATwaLdEUfCwJdSawdBnNU=,tag:uHfrX90nIqtlgPdvvBblPg==,type:str]
            - ENC[AES256_GCM,data:/F7tUWF77S7v+FMUGVISt5KsZkA6vC8bapZmyDMXMxQ=,iv:lOcFVwecYU7wfS3zsPWe3SIrvnCro5BhqOcfL6lzncw=,tag:jP/GPxBIt4T4P5LnO1WZbA==,type:str]
        allow-credentials: ENC[AES256_GCM,data:O3naog==,iv:Sg1RRUFDi7wRmigit7bie3xE12MnzP3QgJcdl+E77ek=,tag:tq+IzYV42jS2ppJczhOMWQ==,type:bool]
services:
    fastapi-worker: ENC[AES256_GCM,data:q08lLkqwO5+WvA7tSQiS7lAKayViasV61JL6AGMMAE9jZ0H2LNsQt38RuO01hXWOa8Qzwu37d4jwIMdhCQJ5iINAzKYzDCsTIzeEco7nOD6HAv4JYUE=,iv:9aIecbL0CN9nv/+AUh2UFnMZhTOkNdpYGgPdIUdjaA4=,tag:ez5YUPGWnWsR2yRlOOFTTQ==,type:str]
sops:
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbnYzSzhVSUxCbDRnU05L
            amJIdzFWeWZ5N2pEVW9qVzRjMUFkb1RaNENBCkF5eDV2NUNWbEZMMG1VenI3dTMz
            eEdnVG9jbnVPS3VtVWxXQmQ2eXhTQWcKLS0tIFZRQVBLakJMZmVuM3QzU3pKMjJs
            SDRZUGZINm5UVG5CYXcyU2hiMDJQV2cKX6TpbBxfoQO7+/RQWOgnQ2SlyKO2Eyhn
            t7J3Hlo4lrl9nxTqPNyWXPG8lYrID/ACHkdFZZsrVsedgGFc3dFKJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYVAwOWhIaW4yOU9RR0ti
            UGZLNjJxTU9ETGhmeUZRUXR0ZnQvTUFzdmw4CkNwYnorczhRcStWeWhRVU5Ic3Jw
            dXFna1czc2JlYVdLTSthajFIdkowSlUKLS0tIE5SWkNydVVvZ0hGNEcxTUxiK0hC
            dWIrQ1ZaNmI5b1A0blBERGtWdnp4c0EKDFwbFVQAm7i9EC+XrYsUoFtuZojUpOm/
            8MARCXKRWrjLPZs8sjQkeqirXlLSNNXilSG4risgArhtm7sHDBkrqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq6xtpmyzsum0fc2uk2dwda6rksp6dd8v2m654ev604d4n65cu8synu99s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbUNIQTBEVFJPd3JBUFhy
            UG5vZlkydVh3RERkRWUzNmFidEJaYWhEQVdZCm9XZ1Z2eVVzTUZGdHl5a3lsbS9D
            cjdhUkpvNEZGejdZcmJ0QzN6T3p4dGcKLS0tIDk0Nk0yUDdqd0xiZ3lIcDZyZyt0
            N2M0TUdqMmxmNkdITUVIcmVxYVlUakUKtRRN8TyKS94PQlWbWdNJY7aJ548Eyhz/
            2emvXEOeZONrgXyBcW+vCH7gZ8YUfzO2wX3YHOqyf2UpzXoubSrTWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zfr86gs33mx2lfpc0083lweet3za5ufu0wsfqch4fe2glpdqqdsq0mjp6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ0lrQ0FmT3I5K2NsVDN4
            Q1ZOS1dBa0ZOOEwwUVoyVzdyODhoUys0akFRCkNydDRibDlQaFkwYUN5VVdGNFo4
            WjNqdEVkQmphZVRvci84SDltRTc0TlUKLS0tIC9qankyUFR1MC9qaWM0bUZpY1Nm
            WUdTK0h6Uk9TaVdrU3NiTVJUaVZGcE0KXN76mI1AmZEUYmQ6e7rn6WMo3ySg0kBq
            hIK1oD1zvIluRBY0VdDCM+gBSBegKrWxVQj6bgP6WqQFl3FpTe8oUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pg2reqfck7et78amrcvvzlp7zjm5hy8vg8em70mqv5ww5ark6f5s5xvpvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdUJUU0RSUWQyMUVXWndW
            NXNpNFVNUkJyYlRBV09MbytaQ3NFWXpsam1rClhzYkhPNlZUR0xJajFIRWNYdGJQ
            ZmRWbWdiSkJ2WnYxN2drUjlSa1NnWEUKLS0tIDk5andvTDRZK2luaGI4QzlvQ2VB
            eFVTTmpnMGpQY2dUcVpCSFl0SU9ONUEKxNo4IZ//zm370lOMZa8G78h6sFhLjCDS
            i0wRPSCz2VPaeI+qOm0J4hnzbRdXJuOO2XGXjn48e3MrrN8RbL5ZrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsaevml5lg2qknhn7wvzwwguzglygzll59nx8f54l9tlhqp405usljrprf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZU9Ua3YrNFZZUHJaLzdR
            cW92eDJMWlc3amovV3poRWc2dFFqWW5zWWlZCkY0N1MxNUFCajZVYVNpV1dROXFQ
            QWYvRlNPYWtBOTY0V2VqdVJoZmJ4eU0KLS0tIFRzOU91eG9Ua3R4R2lzd1hRYVdH
            Nld2b0VsWkl2SzZmRm5OYjhUc3Vsd2sKq9ko96nfucuUolCraqtGtUOz5qV++nel
            AVloijwLz+3t67o0CNjPnfooY9ZcnuHj/QUiPP7DEom2nJqVlhaOCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T04:52:14Z"
    mac: ENC[AES256_GCM,data:aUhMoHUd6o02U4lV5PxkgyAZ/dtm7YFCO9tkHdDDnWHFpGwO79YRgAbJ06UEO5JyytCbR713VhkrHO+G4boVjhiCc2c5Sd86+/e2IKukiwEtocHIC4UqNxgZtvr4yzeXPFCTkFPyiWog3OatNiZx6k4agLQ63NgscmjUVKPSC9M=,iv:f53cAYBIMrARGSWybna8Cx6fh36AHfBgxlelJNBwDp4=,tag:2CgCiyxbnF3nT9OimQE6UQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
