jwt:
    secret: ENC[AES256_GCM,data:Qnza+jG1bnjcoWDE,iv:eFOnHjWNcE06FIbRnZzRg1fTRvEIkyOUg6YtKFc2rXg=,tag:l+kGonF9YH8ouBrA5tbaEA==,type:str]
azure:
    containerName: ENC[AES256_GCM,data:SQ2izSVLUs9HjL9LR+XC1BDU/H9F4w==,iv:g6l5onMGlPHQfmEHIQyWFeyGEuAlyNVrbvF2ZUvhFuc=,tag:2ItiZz1G4mz+D8/zenuOWg==,type:str]
    storageAccountName: ENC[AES256_GCM,data:A/VcVa4Uj/GPtza9hoZrqJJ3,iv:gBbPziqG3kMpoJHjSkpnD4wSE8cdo1s+qvv9JCv2nQ4=,tag:2GGlHXujV4Qmxq7B5m3oNA==,type:str]
spring:
    mongodb:
        uri: ENC[AES256_GCM,data:Jlvuy0tkesvGAdTTMnFzSyrnWpvGT700K+aGYSxb9vrRWdWobm2W9yAoqN9HMf1wlhv357LEKzhd3mYBfHO3gNalh+3HTMvk1hvp0yTsGQt1MH1JduLiBtnf2peGvkFwLPYhMA==,iv:IxpAI8eSgf24WIZe+TA91xsM/lH7YtDSmV3G4TrnR44=,tag:SgFjrUWPM25xQ3Hkl5tuZA==,type:str]
    data:
        mongodb:
            auto-index-creation: ENC[AES256_GCM,data:+gZJzQ==,iv:19Ats8jKKOvuO9K8In5rAUQqkc9z46Pp9oCSYWhoKvw=,tag:mbRH4rrqYdlq7vn4jgCvxg==,type:bool]
server:
    port: ENC[AES256_GCM,data:nKlcDA==,iv:r9G9t12NH9wDf8jh3i3CrZJXtOJNf1ylBW9NGNMzkGg=,tag:4ElAns0sOLJq9AhKO/rcXw==,type:int]
web:
    cors:
        allowed-origins:
            - ENC[AES256_GCM,data:27Gg/mxb0dSRj+PbikaPeR6sw1JiDqCazMHgfNLf2rnD0j6tZmO/YxTS,iv:iwf/rhuP5tL80GShnwnyjWf4b9gMyCMS4t4GIPYgUvs=,tag:/K8onYtWBjNHa+SpFDLNhQ==,type:str]
            - ENC[AES256_GCM,data:iQ2REEyU/1rbhV7NXmi4SsGYF9qZzLrSaMjXGM2gTu3N5b2Rpb2d82I=,iv:2o3RmBwbshzWOjND3fV/WMKjXVzT8opmUrN4T9dzLbA=,tag:NZBfrF0blzQ2yoxTSXg+yw==,type:str]
            - ENC[AES256_GCM,data:kvoWVsuk8Bz92aqeJ/udDBcv66X4ZWB0EYEMl3mnuw==,iv:BPIs3eDJLxQrWuJLM8u0jxpetJ1mPc6j4/0x/Lg9rK4=,tag:0YxrQBhzbhdq1p1l62ZoPA==,type:str]
        allowed-methods:
            - ENC[AES256_GCM,data:VZzd,iv:33gHXwI640iJ1P/AMtIG7FXA0SJLcSJzygG5Erv/Y2I=,tag:kdMxIUHxXDciVkta7/ti4w==,type:str]
            - ENC[AES256_GCM,data:at2jyA==,iv:8IZ9Mx8Mm4iPb9YhdE9dK3eKrAr7+KaD778aFGjnr/U=,tag:99pYFJjahgFuyuKBNNVZbw==,type:str]
            - ENC[AES256_GCM,data:gWmQ,iv:wwzsVBCGngfwf3ckuVyNwr8w5UKbheOxzFuwkpEkPsk=,tag:OrEl0KTykrG9C1/CJtFSiw==,type:str]
            - ENC[AES256_GCM,data:oNMOjDt8,iv:rNM1F/HyUGQyRzDlO0CMfF8jFb3mKc40V2ekmJhbnJw=,tag:M7HxKtn+hLbTASbXQADjcA==,type:str]
            - ENC[AES256_GCM,data:7O1iS3Oghw==,iv:hyBIEv5s1ak+66jkJ4L6YC66VlLUBP+FETVFIQBaMz4=,tag:IONpkCcm+dEbdrJ1ruriWQ==,type:str]
        allowed-headers:
            - ENC[AES256_GCM,data:CRZvDh3p,iv:XH59pr+BpM0CUtreDIe+UNcWAGGH1IXjT2cLgC9SYKE=,tag:3DZNWIU+QpmlzTLtW9fZ6w==,type:str]
            - ENC[AES256_GCM,data:uC4HNRs7nKBj7AK5u2s22kDz4XDVSVv2ZCJL,iv:6s49s8+l6sptOpwnYFLW351T5d5hTPrcBLyjY6aQnTY=,tag:Pbu2MPlw1oasOVuZBPclag==,type:str]
            - ENC[AES256_GCM,data:zGMIQvbPfbXXdJvQ,iv:lVn+vCzN+PeQF4YhkhbOu5+3yrU6OTlmsK46fpx7FcI=,tag:5r/LHZunYCzz8s5uAb20KQ==,type:str]
            - ENC[AES256_GCM,data:VNzALnCN,iv:aNJtmRk3iOMO8pYBpGPZBlOIx0ZEl1k7LE8nvLgGhDk=,tag:Zgje/6tPmLLxaeoAyzG2Zw==,type:str]
            - ENC[AES256_GCM,data:K7QN/rqGqMIk,iv:b/zC1xpntbxYZsY6Lqhk+eBGwgYEThIkU5FsHqMIOdw=,tag:57SswkFWH0MmvHK9Ze99FA==,type:str]
            - ENC[AES256_GCM,data:7TpxhQIKQtOH2yA/3w==,iv:YN5D1wQC1si4JrnGQ4QIUiM8vw7/hwjBiLsMMT/O0mU=,tag:Vu3IhCnmcuH+eAc+TD1OvQ==,type:str]
            - ENC[AES256_GCM,data:P3MoUQPn,iv:hG9AHSoeWgjTXwKEjo20/56Kvj0358yk5DtBhuKJJn0=,tag:kQHnrd+POqedgS2jNqq9ng==,type:str]
            - ENC[AES256_GCM,data:5UWOJRRdShptk3Lajt2u2g==,iv:JHPOfa6MFO5aOAyPckHF9xOWKBZP7Qki04DVd00Qixo=,tag:6XH94iaqgX7jPrqYFt7rkQ==,type:str]
            - ENC[AES256_GCM,data:ZJj33jTAU5b2+ScOpW/kXwFAfVajy6KW5pQbd+4=,iv:jMp/TR1Ig9Ds+vKPaJ4fcX/6PPL6gJlhIiG7grDnFHo=,tag:GuSQ9ZB9m7i1iFGm2Ep8Dw==,type:str]
            - ENC[AES256_GCM,data:JojMOyvcE4D4pukEp3vcexdVqc+CXY/ut0t8GBUU,iv:+h6fwdYcP18cU6SQLzwCBxyzx6nq14uveeK0l0tkI1A=,tag:4mK24G+FHeez5QWMmRtXEA==,type:str]
        expose-headers:
            - ENC[AES256_GCM,data:xlCLeV+4,iv:ziG7UspgvSw6hxkzpgTo4L22PO3YbRYDQRK3gwQ8dFw=,tag:GmZyoca3GnzBedL+A1fFfw==,type:str]
            - ENC[AES256_GCM,data:/dfx57iQTwibiKiJ,iv:NUUDKvv5BHRhtthXCmbFc5sV8qYM4U40Xm+goAx6yLk=,tag:If3pBZEts9ZgZLobxtBtFA==,type:str]
            - ENC[AES256_GCM,data:1oGqEQ+W,iv:aE1R5rzeyu35p6tZuDKliE2bokQwlrM3JMfYDbf/5Bo=,tag:uHuY92i4iZPtbTwqb9qErQ==,type:str]
            - ENC[AES256_GCM,data:upNdHWqgKgLh,iv:Zg4AZ4iqVX4XvcBcHtqwp3kdO7ZluTfDzqw5bS5efZY=,tag:+St+nJO9MrW/e5ek57MPIQ==,type:str]
            - ENC[AES256_GCM,data:A6yIsT4gjv8orJcb8A==,iv:S3FbZMNa7TKgkqCPHfz+jDrBt5T5BOdvOS9KxeEvyWs=,tag:26U0HoIu7O8rYo8S2Lxyxw==,type:str]
            - ENC[AES256_GCM,data:nSy/I4dM/fEK8GwnKWI80c+qM+R8uaWarEPN,iv:k1aocQEVYwZJfgxVRvygA/o9wFMeAwDBKVk7a153PTk=,tag:m5JxPC57ZH/1ElygXfZQPg==,type:str]
            - ENC[AES256_GCM,data:7TI6iAFHIxJJdBwGAEDFR265MXxFxMDLfhObe/BeWIc=,iv:KKh70tIvbRdf0UaT2WTjKy5DFOu6UpKKjyr4X64ahvk=,tag:go81yoJpUbnv26nhcBOMEQ==,type:str]
        allow-credentials: ENC[AES256_GCM,data:G+EBnA==,iv:hmTyLn9dND98eBIz+yLAgZkJvkwkJqavYVjLg+37hDc=,tag:9yu8jhEsFWU+M9AHlxIQ0g==,type:bool]
sops:
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdVJ2QWRxQ281YzJSamw4
            N0ZLQVJad1RFb3I3QURFQkdqVHBYck1sWUQwCmdXakw5dW5NVUdYVTBadUtqZFFI
            Q3p0L2pBbTJ0bCtaNjNkbDc1YURxWUkKLS0tIHhrdHpWVFhObG9YU21TaitTK2NF
            ZHpoMmxxcW1xRGJnbXN2eFpubHN3WVkKm2JDMJC9kpbykA4eT4OuwvR/vjCWiv2u
            qzNZM68aPBgGPM5JuIs0IfAcbyRAqV30TUeOHf+zbD7x726N1+qR2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTXlab1dPRTIyWFllNU85
            Y2FBS1oyWW1YSlJEZUxiNmZ5YWdBZnNQUUJzClFJT0R5amIxUURCemp2WHZsWkJ2
            SW9rUm5KNys3MThJSzY4RU8xb2RUeVEKLS0tIG9SZGU2b0hSWkRCd0xlL1BCWm9Y
            YXR2QkI4blZYOE1LMWlkRVlrak5vcDAK20B1FtAtUC/KSl7TDb91vzGJfRgXweUN
            w/ZMpBriJPD/Ui0I/+qi8yto3sFtRzaCceazx/nmG1l8Zt3j5FK9Hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cq6xtpmyzsum0fc2uk2dwda6rksp6dd8v2m654ev604d4n65cu8synu99s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YjJoL3FURnp2RG80WWU0
            VTVXV0NXUzFGUVNvUEFHYVQxbVpuUUpKOXlVClEyZGY1eGRxaHM3YmMwM0dHc3Ry
            SndpbUdWOW5RakNVK3NtYStGRnpBTGMKLS0tIFlYZmdhWkVlU3BDc2VkVHNrSEpZ
            WmhpS1Jnb3dtU3JWS0t3WHFjSlY5TzgKts5hdlcIgFIWB6UAcpTKJldpG48AAVK2
            tbb3nKAvPe9XA/zDeucyekrwSY3PVHj0QH28Nu8DVvs//k1RXq3TaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zfr86gs33mx2lfpc0083lweet3za5ufu0wsfqch4fe2glpdqqdsq0mjp6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UWNobUlXUWFPZHZsWkpn
            TFF3NzZiT0FFYXk0YmgxZGJ2ZStOcmhhaFg0Cmt3b09FaXQ5UGdmYytxSUpiYlM0
            ckZBdWh0bDBEK3dWQklpdGRsOEtGMHcKLS0tIE8xYUt3MnNENEFJWUYzd1lRb2sv
            YkpGYnVmenkzeGQ4TUtDMjlVbGEweVUKKS1I41F/XIW/YK0RJALk9eBjNYwzxrQW
            cyxJiFlvSW97eSXRWuluK+xtrrmVyU4iZiRDkpRvCFXKUo3RhKhTmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pg2reqfck7et78amrcvvzlp7zjm5hy8vg8em70mqv5ww5ark6f5s5xvpvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvemU0anBVSHJQa085Tjhs
            OSt3cWQyZjBjWUIzcFIzQ3IzVzgyeUxwajFJCmsxNVNkMTB5TkFxb2lBQkowU0lM
            c2ZpbkZ4ZlZUeWkrZmtYRWtNU283azgKLS0tIHZMRkVwejRTcEM0L1NUL1ZKOVl0
            d1lxVjBVeUxWQ0NCZzcyVDBuNHE2bncKhd1tvz3S6nj2JnlzbHDViqtXQnXvi/pz
            vA7S2A2ty/3jrVvahFVKqQISKDyJQ3Ld+9pvi7roL2Il/MfduFFn4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nsaevml5lg2qknhn7wvzwwguzglygzll59nx8f54l9tlhqp405usljrprf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNnJ2TXZzSEJFeHRSTk10
            SVE2SHZhUlhFczdNVDAwUXJYY3BtVkNEeDM0CnJEcEZveTY3c01XVGhkRnJiWjJl
            WGYreTk2cUFkUHdGRmRYT3JPMlNUOVkKLS0tIExDcTBaWUh2bjBwS3ZlODlaWUhZ
            ckJaSGRuTExhbnJVR2tEMHhwcVF3WXcKQVgH7s2IW2RPDLdB0kQfCPzKmQpAbNWE
            Fy+JpRiYIIvwtujDJAFnubTEy86VXsK3FRXLbZdQreOA+nelP0fi6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T02:53:31Z"
    mac: ENC[AES256_GCM,data:WHz9N59e87+49fvHYO5Id/JbwLRbJRY/TbR/p2vtTQLeCRkcRJmribDfeenyiSScILa20hv2MOJ68dcIPDUQCEVAfZ9qJbTo+Iw8WRmtdGfRJIaNQDPXirz5NL+cYQYRR1eQ888atVqzr+gAH2OmRMLWeSQqjVu38oANuvKgsaM=,iv:yYSBygBAJdjLJkWY6VzdjG7XUrR9PYUnqXPZfZNC4Is=,tag:3SHPbkQulpcAKgGF1c7H4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
