jwt:
    secret: ENC[AES256_GCM,data:/Z8owf7/oFcx9i7w,iv:5EGDwDTMRjIxrG8WWchI/AyZObr5ndlKkhL7vy5p+r0=,tag:H29JDurlcufdfhb0UyV0pA==,type:str]
azure:
    containerName: ENC[AES256_GCM,data:MDx7vFR7RKO/+zBfWmfNYHCHMpVpoQ==,iv:xaqgAMyxUzEslVYvcnZwsjRGFhqyt/iVr1mUMqRf8vY=,tag:AIQGYU3aAewOzw6xiaakGQ==,type:str]
    storageAccountName: ENC[AES256_GCM,data:ZVoQnIsgPxG4LlaamQMMY5Xa,iv:JiyjxUKvjajwE/R3EbTUpTwl4tFlSmD5LJwa4UL2fEM=,tag:jCZTdMZjun70g31XzINqnQ==,type:str]
spring:
    mongodb:
        uri: ENC[AES256_GCM,data:AEttB+GqqmQ6VLzjNHP4XRsla+qKRJ47bs4/Eiw7/rBDi5f5PeM62xfV4CdQKyR91VPAth+rs+bi7GMwm4sZWRneoG0k6FpclEb+4/yLjp6g2ms0EjOqgfEi+A3mj98QykXtPw==,iv:CNP8BCy23SOSTaDCxX1M9HCi/NR1jmOtmmEnGZZFZCM=,tag:maykPaP8u51GGdZYJK0zDg==,type:str]
    data:
        mongodb:
            auto-index-creation: ENC[AES256_GCM,data:QnwvyA==,iv:DgjjvKYKZFyRbrgEM6eITYfoeCpqwhfStb5uFwOtBec=,tag:MjeV1BNFB4r8hfZewxZ+Vw==,type:bool]
server:
    port: ENC[AES256_GCM,data:xNswoA==,iv:5UX3Qt92WaW70uVhhlQP7hB6d2SDFlj7sFeNKMIhOkE=,tag:OcSjMFlpA23DuF+Ixsbo7w==,type:int]
web:
    cors:
        allowed-origins:
            - ENC[AES256_GCM,data:qU1FswgJyK0Uf0IjJ6QLWp0uT7x5p05OcYR/6j9lqJVYtjt+veqrAJYH,iv:3g4weu7DjrRlnR29XIXlClWcOT35FmNXSY3+NiexoUM=,tag:doZTqHt2HFAozU6TNhWNuQ==,type:str]
            - ENC[AES256_GCM,data:7gVfQN8F+uHX+jbezvw7kgdp2fM4pX0+uSF2eMMtG9Nz5nzHv0p7Hg4=,iv:lRh1WU3d+PxarXPFLBXToKE5aEhn90nDgmOJMOAsO4o=,tag:1mGUeLOuUIPG1rTOCGGWBw==,type:str]
            - ENC[AES256_GCM,data:5J8u8kw1Entll3+tdNt+J1lUwWfZnJEHA4eDcLlZrA==,iv:wD3YPibRalSKFXBs67u9Y4uvQZO6QZbmjLpracB4TL4=,tag:Jl4D163vx7a+EbTVqSxudw==,type:str]
        allowed-methods:
            - ENC[AES256_GCM,data:N/p8,iv:m/HLa6lM9uDxdXOOvZ+U+CFj6fi+cU5KUKLoHVmW694=,tag:tDOeuNiQMHL+Tmjk+aFxiw==,type:str]
            - ENC[AES256_GCM,data:0YQoxg==,iv:J249lXrf/PdcGwmr5tCk1yjaqCZUvr1eqYVtRUWDgZE=,tag:smMh6gw/QtvnCEA7KDzX+g==,type:str]
            - ENC[AES256_GCM,data:1F16,iv:BSj7/mafdh25OqHD3TDMLRRyyl5FF2jwYWsXZcBiFqc=,tag:d1mG6FLjuOGtfsaAAowHFg==,type:str]
            - ENC[AES256_GCM,data:eUooyd3f,iv:HsoKy3BR7BcgOtKKJxXhSRNU8GXeoUu7NeLvfu6PY/Q=,tag:ipfe/QuKEvMoBs2UVk8G5w==,type:str]
            - ENC[AES256_GCM,data:PaiMqW9suA==,iv:JXjY5nipaAK7Ayh8LfZkgvzV8Mqd1w24wjs56iaOAfw=,tag:mUjmwB4AnRXFC6EmTeXahg==,type:str]
        allowed-headers:
            - ENC[AES256_GCM,data:1L0wM/w4,iv:cersoYbjFIPFnLBU7y1AO4K70Empq8ZJtncXofT3Xmc=,tag:ZRsPYgKhSciR7S1S1eB3Qw==,type:str]
            - ENC[AES256_GCM,data:mFLR28guPLGSqbkxEpugh9qljbLoQrwXJsuJ,iv:YgfL/q5Z6XoCQ7H9niMPf/TFlgHQUrjick7Pf5nW10A=,tag:JLUByEw/xFRHWxHybDgFJg==,type:str]
            - ENC[AES256_GCM,data:VHlC7Fnfb8Nx+OYr,iv:4D00hLG9rzrcGW7FtrD8Kf/N1lxZml2bbot99dXuEYY=,tag:CaduEVNDaxyjwnYIrsdhQQ==,type:str]
            - ENC[AES256_GCM,data:epPWB4BC,iv:Xs/i9Kv796hXNGKftVL9tU6Ez47IseKP2HJ8NNgxeB4=,tag:LQODwyvKbVGmAuk8dQ8Kew==,type:str]
            - ENC[AES256_GCM,data:ML+YfmXXTyu/,iv:lTlmMoFyqq7JCJgDWEsUHcmbDdCigtFv/CIxSRPkRVY=,tag:o3pbPHUlR7v3SNYTfeQXfw==,type:str]
            - ENC[AES256_GCM,data:DCuC8iTuaXrbQrF1OA==,iv:9CPEvRnnYDqLtS06M394FrGk2OTZTo5BgYJpsVVsOTI=,tag:uXaE1YB098eMnhvm7LlpoQ==,type:str]
            - ENC[AES256_GCM,data:2UAppNsx,iv:nDnW/sQIvul7vQZdplkRD3iyJFjOCXiMloc/okY0rGw=,tag:+TcJIvBpC3xO6hIM0yXvWQ==,type:str]
            - ENC[AES256_GCM,data:urMG7Y2mcMdalrNVM7v+yw==,iv:ZYY8R/Wl37yDjYG378t36uvKu3BtrTg7uSRceg15l3I=,tag:tPda4D6jX7wIvtN+EYCXqA==,type:str]
            - ENC[AES256_GCM,data:NjIUtMi0dFIeLzHwDGEZQDOZ2wK9xJOMuLUah2k=,iv:/8iZUdCQJGKpxJDr9OmgxwzbkGxvYeiI8vvHt3fGVaE=,tag:qL4XGDC8Rbun/mNZ6Inu1g==,type:str]
            - ENC[AES256_GCM,data:pJV5H6uxexP7QOh+M8svT+8JoRDU1wzbNUWDcnSk,iv:1ajuBmIuWHA3OBZ3RD6UP227f9l1ujfM8hNitTETZJ0=,tag:Nw6kzGlue8kf7UL2oios2w==,type:str]
        expose-headers:
            - ENC[AES256_GCM,data:rTtay5rN,iv:EhhF2CbAOF4ztZ4IAnErbYrrsNl2kczhW/QeUAeZfoY=,tag:N9XcOWWxSqx80O5PJhbJXQ==,type:str]
            - ENC[AES256_GCM,data:TjT6LuIgjieeoA5Y,iv:Do0NM7T2xHyBtN4Gk2fgRZ9nteZUt/hkLJDLZOnmzwg=,tag:2piWw4mR2sv8im0I7S93zw==,type:str]
            - ENC[AES256_GCM,data:jJwsNk0Y,iv:aRmgO/+gED6nXByrXOUT+80MWqkRop9YbbyVJSa6Ll8=,tag:bUUXx32USG1f7hOdB8lVTQ==,type:str]
            - ENC[AES256_GCM,data:P9dQXFqpLg2u,iv:CzuWYA5hNkoFSYctVF8n41/w0iTSUcGQN7JRJVvFkyY=,tag:sQzXtOATYAU2zRwVhjhCQw==,type:str]
            - ENC[AES256_GCM,data:PdyU1//UtZX6F8ggGg==,iv:aBitamxxFzHfBQoQ53xv227SRFA7MnzrBHCa54DPW3s=,tag:GVLGL6+w2wNfioB3IrcFLw==,type:str]
            - ENC[AES256_GCM,data:H36hg2zTTGmwmUqC+xlz0oAierL7tXAI1Igf,iv:OqG6nNX4q766zqr8iteCiR8tyoKvEDuKpXm5890xEmQ=,tag:nttj7OAQ15ArOnCpfyxokA==,type:str]
            - ENC[AES256_GCM,data:SXMHuRFNCHwEnJbq2m4X3ooHWjSXpH18RsPhKU6C9qg=,iv:LJ6W/i87urtbuYAcV/BUMkezbP2jtD5dUxTTs8Dolz0=,tag:FGu67gO6E7FRr9CupgSmgA==,type:str]
        allow-credentials: ENC[AES256_GCM,data:8s6hZQ==,iv:3XB0k/PdBnZ1jaYOpCcL6/aMQMNjBywz3HTPYfF0ClA=,tag:D4JkjIEdToIEYifVtqlX/w==,type:bool]
services:
    fastapi-worker: ENC[AES256_GCM,data:mgtRnNy+Qqhxb2Ag7kLGM8YrA7OR49VYgZ8UPKr8FY6y+2XCMGb+w0N++xGeTFLBVCG8I6/BKDdDJvRsSx/+C4dzsoJ6Zigjx4c1z5kViw4CaZd4Rg==,iv:YjXqPZjIOglx95wXGgsYkczb0NjYj7+4NCMhCPc3IgA=,tag:nc+ZUt27Qs0MVd7pPaTCwQ==,type:str]
sops:
    age:
        - recipient: age14rfhef89myvcwtngnep3tuc2hq0cukgkgn3w98teaa8sqhttd9pqslq2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3LzVOSll1Z242LzE4bklJ
            bzZnOEZBWmxCcm84aXdOTjdTdnZ5V2F5TUdJCjQ4TFVLQnk5ZmNYNUtZRHNGVDhz
            Vnd4OGI3YnhKNUw5bDR6VGxGN2FKTUUKLS0tIHlsaWRJK0diL2U5MlpYa05RRjVm
            bTBoNHZDN1hXZDFBNUhoWnZPTVhWUzgKA3K9KAXKZot8KOtZQEMygefOFwhzBM3Y
            WcQ0tcpkowSD7pybuibii3KUvR5UvVdhCA0jO0E3qv80hOrvlDgnqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dh8a2ar5vtue8upyxdk9n47uqqpgmkrnst0cr623qszqm9tptv5sx9026c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLK1ZkZWdZbjI1YTc4ZXgy
            MDFnNGxpTmppWXdWV0pncHNhVHA2SXJtaEhBCk1xV1BBdEhWVXA0YXovTzhnQWtS
            emw5akUzOSttelBsbjQ5ZjBYMkFPc2sKLS0tIDlNYS8wdHBxa1djQithQkdTV0RU
            NWd6YlJ4UmVGRUF2cExBTFJ3NElYQjgKu69O+Ku0qZ0sQJSX0kywZ4wsC5dnpdBe
            U+elT22oI7WmFOjRIOBZsf48lGyrnk0Q1VTfrsbrjG1ecXhnXorlig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T00:25:34Z"
    mac: ENC[AES256_GCM,data:pwgPGthl0dH5qLSWdUhcGXpH5Y1tV5HKMyJjKuZUlvdck3DSi1xsmJj/H3gSg/DLCztzvDn5IuAAOD5Vv8VyC+Kl5YmXyWK8bNTCstJ2Z9NZHHOVAXwsY9wkOwOVHX06v0aK9Fg0VOL3h05gvijDT49fBBZWhCbGa7yZP0lKXy8=,iv:02guRBXG7Euw3qdyxtrAwy4W81PZtkFNHTzsp1hLki8=,tag:GHINiL139MrFicu3CgTjHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
