name: build_deploy_aks
env:
  JAVA_VERSION: '17'                  # set this to the Java version to use
  DISTRIBUTION: corretto              # set this to the Java distribution
on:
  push:
    branches:
        - 'kubernetes'
    # paths:
    #   - "kubernetes"
    #   - "src"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: 3.7.3

      - name: Setup age
        uses: alessiodionisi/setup-age-action@v1.3.0

      - name: Run SOPS
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_SECRET_KEY }}
        run: sops -d src/main/resources/application.enc.yml > src/main/resources/application.yml

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package && ls /home/runner/work/open-chemistry-lab-backend/open-chemistry-lab-backend

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Build and push image'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.registry }}.azurecr.io
          username: ${{ secrets.service_principal }}
          password: ${{ secrets.service_principal_password }}
      - run: |
          docker build . -t ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
          docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}
          
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'development'
          manifests: |
            deployment.yaml
            ingress.yaml
            namespace.yaml
            service.yaml
          images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}:${{ github.sha }}'
          pull-images: false